// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyManagement.Models;

#nullable disable

namespace PharmacyManagement.Migrations
{
    [DbContext(typeof(PharmacySystemDbContext))]
    [Migration("20260706163049_KhoiTaoCSDL-version2")]
    partial class KhoiTaoCSDLversion2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyManagement.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogID"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableName")
                        .HasColumnType("int");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AuditLogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Batch", b =>
                {
                    b.Property<long>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BatchID"));

                    b.Property<long>("BatchNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("GoodsReceiptItemID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("BatchID");

                    b.HasIndex("GoodsReceiptItemID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Batch", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Branch", b =>
                {
                    b.Property<long>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BranchID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("PriceListID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchID");

                    b.HasIndex("PriceListID");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CustomerTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerTypeID");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.CustomerDebtSummary", b =>
                {
                    b.Property<long>("CustomerDebtSummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerDebtSummaryID"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Increase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerDebtSummaryID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerDebtSummary", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.CustomerType", b =>
                {
                    b.Property<long>("CustomerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerTypeID"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerTypeID");

                    b.ToTable("CustomerType", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.DestroyReceipt", b =>
                {
                    b.Property<long>("DestroyReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DestroyReceiptID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("DestroyReceiptID");

                    b.HasIndex("UserID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("DestroyReceipt", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.DestroyReceiptItem", b =>
                {
                    b.Property<long>("DestroyReceiptItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DestroyReceiptItemID"));

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<long>("DestroyReceiptID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DestroyReceiptItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("DestroyReceiptID");

                    b.ToTable("DestroyReceiptItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.GoodsReceipt", b =>
                {
                    b.Property<long>("GoodsReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GoodsReceiptID"));

                    b.Property<long>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ReceiptNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("SupplierID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("GoodsReceiptID");

                    b.HasIndex("BranchID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("UserID");

                    b.ToTable("GoodsReceipt", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.GoodsReceiptItem", b =>
                {
                    b.Property<long>("GoodsReceiptItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GoodsReceiptItemID"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("GoodsReceiptID")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicineID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UnitID")
                        .HasColumnType("bigint");

                    b.HasKey("GoodsReceiptItemID");

                    b.HasIndex("GoodsReceiptID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("UnitID");

                    b.ToTable("GoodsReceiptItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryTransaction", b =>
                {
                    b.Property<long>("InventoryTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryTransactionID"));

                    b.Property<long>("ActionBy")
                        .HasColumnType("bigint");

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ReferenceID")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("InventoryTransactionID");

                    b.HasIndex("BatchID");

                    b.HasIndex("UserID");

                    b.ToTable("InventoryTransaction");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Invoice", b =>
                {
                    b.Property<long>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceID"));

                    b.Property<long>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("InvoiceID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserID");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.InvoiceItem", b =>
                {
                    b.Property<long>("InvoiceItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceItemID"));

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InvoiceID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UnitID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("UnitID");

                    b.ToTable("InvoiceItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.ManuFacturer", b =>
                {
                    b.Property<long>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ManufacturerID"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ManufacturerID");

                    b.ToTable("ManuFacturer", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Property<long>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MedicineID"));

                    b.Property<long>("BaseUnitID")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DefaultRetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultWholesalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ManufacturerID")
                        .HasColumnType("bigint");

                    b.Property<long?>("MedicineCategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("UnitID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VATPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MedicineID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("MedicineCategoryID");

                    b.HasIndex("UnitID");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineCategory", b =>
                {
                    b.Property<long>("MedicineCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MedicineCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineCategoryID");

                    b.ToTable("MedicineCategory", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.PriceList", b =>
                {
                    b.Property<long>("PriceListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PriceListID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriceListName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PriceListID");

                    b.ToTable("PriceList", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.PriceListItem", b =>
                {
                    b.Property<long>("PriceListItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PriceListItemID"));

                    b.Property<long>("MedicineID")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceListID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WholesalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceListItemID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("PriceListID");

                    b.ToTable("PriceListItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Property<long>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PromotionID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionID");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.PromotionItem", b =>
                {
                    b.Property<long>("PromotionItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PromotionItemID"));

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MedicineID")
                        .HasColumnType("bigint");

                    b.Property<long>("PromotionID")
                        .HasColumnType("bigint");

                    b.HasKey("PromotionItemID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("PromotionID");

                    b.ToTable("PromotionItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseReturn", b =>
                {
                    b.Property<long>("PurchaseReturnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseReturnID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SupplierID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("PurchaseReturnID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("UserID");

                    b.ToTable("PurchaseReturn", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseReturnItem", b =>
                {
                    b.Property<long>("PurchaseReturnItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseReturnItemID"));

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<long>("PurchaseReturnID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseReturnItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("PurchaseReturnID");

                    b.ToTable("PurchaseReturnItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Receipt", b =>
                {
                    b.Property<long>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReceiptID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiptNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Receipt", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleID");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.SalesReturn", b =>
                {
                    b.Property<long>("SalesReturnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalesReturnID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("SalesReturnID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserID");

                    b.ToTable("SalesReturn", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.SalesReturnItem", b =>
                {
                    b.Property<long>("SalesReturnItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalesReturnItemID"));

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SalesReturnID")
                        .HasColumnType("bigint");

                    b.HasKey("SalesReturnItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("SalesReturnID");

                    b.ToTable("SalesReturnItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockAdjustment", b =>
                {
                    b.Property<long>("StockAdjustmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockAdjustmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("StockTakeID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("StockAdjustmentID");

                    b.HasIndex("StockTakeID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("StockAdjustment", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockAdjustmentItem", b =>
                {
                    b.Property<long>("StockAdjustmentItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockAdjustmentItemID"));

                    b.Property<decimal>("AdjustQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<long>("StockAdjustmentID")
                        .HasColumnType("bigint");

                    b.HasKey("StockAdjustmentItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("StockAdjustmentID");

                    b.ToTable("StockAdjustmentItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockTake", b =>
                {
                    b.Property<long>("StockTakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockTakeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsBalance")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("StockTakeID");

                    b.HasIndex("UserID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("StockTake", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockTakeItem", b =>
                {
                    b.Property<long>("StockTakeItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockTakeItemID"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DifferenceQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StockTakeID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockTakeItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("StockTakeID");

                    b.ToTable("StockTakeItem", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SupplierID1")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SupplierID");

                    b.HasIndex("SupplierID1");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.Unit", b =>
                {
                    b.Property<long>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnitID"));

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UnitID");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.UnitConversion", b =>
                {
                    b.Property<long>("UnitConversionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnitConversionID"));

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MedicineID")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitID")
                        .HasColumnType("bigint");

                    b.HasKey("UnitConversionID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("UnitID");

                    b.ToTable("UnitConversion", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFailedLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.UserBranch", b =>
                {
                    b.Property<long>("UserBranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserBranchID"));

                    b.Property<long>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserBranchID");

                    b.HasIndex("BranchID");

                    b.HasIndex("UserID");

                    b.ToTable("UserBranch", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.WareHouse", b =>
                {
                    b.Property<long>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WarehouseID"));

                    b.Property<long>("BranchID")
                        .HasColumnType("bigint");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("WarehouseType")
                        .HasColumnType("bigint");

                    b.HasKey("WarehouseID");

                    b.HasIndex("BranchID");

                    b.ToTable("WareHouse", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.Models.AuditLog", b =>
                {
                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("AuditLog")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Batch", b =>
                {
                    b.HasOne("PharmacyManagement.Models.GoodsReceiptItem", "GoodsReceiptItem")
                        .WithMany("Batch")
                        .HasForeignKey("GoodsReceiptItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.WareHouse", "WareHouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceiptItem");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Branch", b =>
                {
                    b.HasOne("PharmacyManagement.Models.PriceList", "PriceList")
                        .WithMany("Branch")
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.HasOne("PharmacyManagement.Models.CustomerType", "CustomerType")
                        .WithMany("Customer")
                        .HasForeignKey("CustomerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("PharmacyManagement.Models.CustomerDebtSummary", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmacyManagement.Models.DestroyReceipt", b =>
                {
                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("DestroyReceipt")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.WareHouse", "WareHouse")
                        .WithMany("DestroyReceipt")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("PharmacyManagement.Models.DestroyReceiptItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("DestroyReceiptItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.DestroyReceipt", "DestroyReceipt")
                        .WithMany("DestroyReceiptItem")
                        .HasForeignKey("DestroyReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("DestroyReceipt");
                });

            modelBuilder.Entity("PharmacyManagement.Models.GoodsReceipt", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Branch", "Branch")
                        .WithMany("GoodsReceipt")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Supplier", "Supplier")
                        .WithMany("GoodsReceipt")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("GoodsReceipt")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.GoodsReceiptItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany()
                        .HasForeignKey("GoodsReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Unit", "Unit")
                        .WithMany("GoodsReceiptItem")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Medicine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PharmacyManagement.Models.InventoryTransaction", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("InventoryTransaction")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("InventoryTransaction")
                        .HasForeignKey("UserID");

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Invoice", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Branch", "Branch")
                        .WithMany("Invoice")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany("Invoice")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("Invoice")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.InvoiceItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Unit", "Unit")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Invoice");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.HasOne("PharmacyManagement.Models.ManuFacturer", "ManuFacturer")
                        .WithMany("Medicine")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.MedicineCategory", "MedicineCategory")
                        .WithMany("Medicine")
                        .HasForeignKey("MedicineCategoryID");

                    b.HasOne("PharmacyManagement.Models.Unit", "Unit")
                        .WithMany("Medicine")
                        .HasForeignKey("UnitID");

                    b.Navigation("ManuFacturer");

                    b.Navigation("MedicineCategory");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PriceListItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany("PriceListItem")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.PriceList", "PriceList")
                        .WithMany("PriceListItem")
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PromotionItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany("PromotionItem")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Promotion", "Promotion")
                        .WithMany("PromotionItem")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseReturn", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("PurchaseReturn")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseReturnItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("PurchaseReturnItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.PurchaseReturn", "Purchase")
                        .WithMany("PurchaseReturnItem")
                        .HasForeignKey("PurchaseReturnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Receipt", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmacyManagement.Models.RefreshToken", b =>
                {
                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("RefreshToken")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.SalesReturn", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Customer", "Customer")
                        .WithMany("SalesReturn")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("SalesReturn")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.SalesReturnItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("SalesReturnItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.SalesReturn", "SalesReturn")
                        .WithMany("SalesReturnItem")
                        .HasForeignKey("SalesReturnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockAdjustment", b =>
                {
                    b.HasOne("PharmacyManagement.Models.StockTake", "StockTake")
                        .WithMany()
                        .HasForeignKey("StockTakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("StockAdjustment")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.WareHouse", "WareHouse")
                        .WithMany("StockAdjustment")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTake");

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockAdjustmentItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("StockAdjustmentItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.StockAdjustment", "StockAdjustment")
                        .WithMany("StockAdjustmentItem")
                        .HasForeignKey("StockAdjustmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("StockAdjustment");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockTake", b =>
                {
                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("StockTake")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.WareHouse", "WareHouse")
                        .WithMany("StockTake")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockTakeItem", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Batch", "Batch")
                        .WithMany("StockTakeItem")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.StockTake", "StockTake")
                        .WithMany("StockTakeItem")
                        .HasForeignKey("StockTakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("StockTake");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Supplier", null)
                        .WithMany("Suplier")
                        .HasForeignKey("SupplierID1");
                });

            modelBuilder.Entity("PharmacyManagement.Models.UnitConversion", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.Unit", "Unit")
                        .WithMany("UnitConversion")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PharmacyManagement.Models.User", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PharmacyManagement.Models.UserBranch", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Branch", "Branch")
                        .WithMany("UserBranch")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.Models.User", "User")
                        .WithMany("UserBranch")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.WareHouse", b =>
                {
                    b.HasOne("PharmacyManagement.Models.Branch", "Branch")
                        .WithMany("WareHouse")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Batch", b =>
                {
                    b.Navigation("DestroyReceiptItem");

                    b.Navigation("InventoryTransaction");

                    b.Navigation("InvoiceItem");

                    b.Navigation("PurchaseReturnItem");

                    b.Navigation("SalesReturnItem");

                    b.Navigation("StockAdjustmentItem");

                    b.Navigation("StockTakeItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Branch", b =>
                {
                    b.Navigation("GoodsReceipt");

                    b.Navigation("Invoice");

                    b.Navigation("UserBranch");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Customer", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("PharmacyManagement.Models.CustomerType", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmacyManagement.Models.DestroyReceipt", b =>
                {
                    b.Navigation("DestroyReceiptItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.GoodsReceiptItem", b =>
                {
                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.ManuFacturer", b =>
                {
                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Medicine", b =>
                {
                    b.Navigation("PriceListItem");

                    b.Navigation("PromotionItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.MedicineCategory", b =>
                {
                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PriceList", b =>
                {
                    b.Navigation("Branch");

                    b.Navigation("PriceListItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Promotion", b =>
                {
                    b.Navigation("PromotionItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.PurchaseReturn", b =>
                {
                    b.Navigation("PurchaseReturnItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyManagement.Models.SalesReturn", b =>
                {
                    b.Navigation("SalesReturnItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockAdjustment", b =>
                {
                    b.Navigation("StockAdjustmentItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.StockTake", b =>
                {
                    b.Navigation("StockTakeItem");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Supplier", b =>
                {
                    b.Navigation("GoodsReceipt");

                    b.Navigation("Suplier");
                });

            modelBuilder.Entity("PharmacyManagement.Models.Unit", b =>
                {
                    b.Navigation("GoodsReceiptItem");

                    b.Navigation("InvoiceItem");

                    b.Navigation("Medicine");

                    b.Navigation("UnitConversion");
                });

            modelBuilder.Entity("PharmacyManagement.Models.User", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("DestroyReceipt");

                    b.Navigation("GoodsReceipt");

                    b.Navigation("InventoryTransaction");

                    b.Navigation("Invoice");

                    b.Navigation("PurchaseReturn");

                    b.Navigation("RefreshToken");

                    b.Navigation("SalesReturn");

                    b.Navigation("StockAdjustment");

                    b.Navigation("StockTake");

                    b.Navigation("UserBranch");
                });

            modelBuilder.Entity("PharmacyManagement.Models.WareHouse", b =>
                {
                    b.Navigation("DestroyReceipt");

                    b.Navigation("StockAdjustment");

                    b.Navigation("StockTake");
                });
#pragma warning restore 612, 618
        }
    }
}
