using PharmacyManagement.DTOs.DestroyReceipt;
using PharmacyManagement.Exceptions;
using PharmacyManagement.Mappers;
using PharmacyManagement.Models;
using PharmacyManagement.Repositories.Interfaces;
using PharmacyManagement.Services.Interfaces;
using PharmacyManagement.share;
using PharmacyManagement.Validators.BusinessRule;
using Microsoft.AspNetCore.Http;

namespace PharmacyManagement.Services.Implements
{
    public class DestroyReceiptService : IDestroyReceiptService
    {
        private readonly IDestroyReceiptRepository _repository;
        private readonly DestroyReceiptBusinessValidator _businessValidator;

        public DestroyReceiptService(
            IDestroyReceiptRepository repository,
            DestroyReceiptBusinessValidator businessValidator)
        {
            _repository = repository;
            _businessValidator = businessValidator;
        }

        public async Task<DestroyReceiptDetailResponse> CreateAsync(CreateDestroyReceiptRequest request, long userId)
        {
            if (request.Items.Count == 0)
                throw new BusinessException("Destroy receipt must contain at least one item.", "DR010", StatusCodes.Status400BadRequest);

            await _businessValidator.ValidateWarehouseExistsAsync(request.WarehouseID);

            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(
                request.Items.Select(i => i.BatchID), request.WarehouseID);

            foreach (var item in request.Items)
            {
                _businessValidator.ValidateDestroyQuantity(batches[item.BatchID], item.Quantity);
            }

            var destroyReceipt = request.ToEntity(userId);
            destroyReceipt.Status = StatusTicket.PENDING;

            destroyReceipt.DestroyReceiptItem = request.Items
                .Select(item => item.ToEntity(0, batches[item.BatchID].GoodsReceiptItem?.UnitCost ?? 0))
                .ToList();

            await _repository.AddAsync(destroyReceipt);
            await _repository.SaveChangesAsync();

            return (await GetByIdAsync(destroyReceipt.DestroyReceiptID))!;
        }

        public async Task<DestroyReceiptDetailResponse> UpdateAsync(long id, UpdateDestroyReceiptRequest request, long userId)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            if (destroyReceipt == null)
                throw new BusinessException("Destroy receipt not found.", "DR009", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(destroyReceipt);
            StatusTicketValidator.ValidateForUpdate(destroyReceipt.Status, "phiếu hủy");

            if (request.Items.Count == 0)
                throw new BusinessException("Destroy receipt must contain at least one item.", "DR010", StatusCodes.Status400BadRequest);

            await _businessValidator.ValidateWarehouseExistsAsync(request.WarehouseID);

            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(
                request.Items.Select(i => i.BatchID), request.WarehouseID);

            foreach (var item in request.Items)
            {
                _businessValidator.ValidateDestroyQuantity(batches[item.BatchID], item.Quantity);
            }

            destroyReceipt.WarehouseID = request.WarehouseID;
            destroyReceipt.Note = request.Note ?? string.Empty;
            destroyReceipt.Status = StatusTicket.PENDING;

            destroyReceipt.DestroyReceiptItem = request.Items
                .Select(item => item.ToEntity(0, batches[item.BatchID].GoodsReceiptItem?.UnitCost ?? 0))
                .ToList();

            await _repository.SaveChangesAsync();

            return (await GetByIdAsync(destroyReceipt.DestroyReceiptID))!;
        }

        public async Task ApproveAsync(long id, long userId)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            if (destroyReceipt == null)
                throw new BusinessException("Destroy receipt not found.", "DR009", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(destroyReceipt);
            StatusTicketValidator.ValidateForApprove(destroyReceipt.Status, "phiếu hủy");
            StatusTicketValidator.ValidateCreatorNotApprover(destroyReceipt.UserID, userId, "phiếu hủy");

            destroyReceipt.Status = StatusTicket.APPROVED;
            destroyReceipt.ApprovedBy = userId;
            destroyReceipt.ApprovedAt = DateTime.Now;

            await _repository.SaveChangesAsync();
        }

        public async Task RejectAsync(long id, long userId)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            if (destroyReceipt == null)
                throw new BusinessException("Destroy receipt not found.", "DR009", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(destroyReceipt);
            StatusTicketValidator.ValidateForReject(destroyReceipt.Status, "phiếu hủy");

            destroyReceipt.Status = StatusTicket.REJECTED;

            await _repository.SaveChangesAsync();
        }

        public async Task DeleteAsync(long id, long userId)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            if (destroyReceipt == null)
                throw new BusinessException("Destroy receipt not found.", "DR009", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(destroyReceipt);
            StatusTicketValidator.ValidateForDelete(destroyReceipt.Status, "phiếu hủy");

            _repository.Delete(destroyReceipt);
            await _repository.SaveChangesAsync();
        }

        public async Task<DestroyReceiptDetailResponse> CompleteAsync(long id, long userId)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            if (destroyReceipt == null)
                throw new BusinessException("Destroy receipt not found.", "DR009", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(destroyReceipt);
            StatusTicketValidator.ValidateForComplete(destroyReceipt.Status, "phiếu hủy");

            var items = destroyReceipt.DestroyReceiptItem?.ToList() ?? new List<DestroyReceiptItem>();
            if (items.Count == 0)
                throw new BusinessException("Destroy receipt has no items.", "DR010", StatusCodes.Status400BadRequest);

            var batchIds = items.Select(i => i.BatchID).ToList();
            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(batchIds, destroyReceipt.WarehouseID);

            await _repository.BeginTransactionAsync();
            try
            {
                foreach (var item in items)
                {
                    if (!batches.TryGetValue(item.BatchID, out var batch))
                        throw new BusinessException(
                            $"Batch ID {item.BatchID} not found.",
                            "DR002",
                            StatusCodes.Status404NotFound);

                    if (batch.QuantityInStock < item.Quantity)
                        throw new BusinessException(
                            $"Insufficient stock for batch ID {item.BatchID}. " +
                            $"Available: {batch.QuantityInStock}, requested: {item.Quantity}.",
                            "DR007",
                            StatusCodes.Status400BadRequest);

                    batch.QuantityInStock -= item.Quantity;
                }

                destroyReceipt.Status = StatusTicket.COMPLETE;

                await _repository.SaveChangesAsync();
                await _repository.CommitTransactionAsync();
            }
            catch
            {
                await _repository.RollbackTransactionAsync();
                throw;
            }

            return (await GetByIdAsync(destroyReceipt.DestroyReceiptID))!;
        }

        public async Task<DestroyReceiptDetailResponse?> GetByIdAsync(long id)
        {
            var destroyReceipt = await _repository.GetByIdAsync(id);
            return destroyReceipt?.ToDetailResponse();
        }

        public async Task<DestroyReceiptListResponse> GetAllAsync(int page, int count, long warehouseId)
        {
            var paged = await PaginationHelper.GetPagedAsync(
                (skip, take) => _repository.GetAllAsync(skip, take, warehouseId),
                () => _repository.CountAsync(warehouseId),
                page, count);

            return new DestroyReceiptListResponse
            {
                NumRecords = paged.NumRecords,
                TotalPage = paged.TotalPage,
                DestroyReceipts = paged.Items
            };
        }
    }
}
