using PharmacyManagement.DTOs.StockAdjustment;
using PharmacyManagement.Exceptions;
using PharmacyManagement.Mappers;
using PharmacyManagement.Models;
using PharmacyManagement.Repositories.Interfaces;
using PharmacyManagement.Services.Interfaces;
using PharmacyManagement.share;
using PharmacyManagement.Validators.BusinessRule;
using Microsoft.AspNetCore.Http;

namespace PharmacyManagement.Services.Implements
{
    public class StockAdjustmentService : IStockAdjustmentService
    {
        private readonly IStockAdjustmentRepository _repository;
        private readonly StockAdjustmentBusinessValidator _businessValidator;

        public StockAdjustmentService(
            IStockAdjustmentRepository repository,
            StockAdjustmentBusinessValidator businessValidator)
        {
            _repository = repository;
            _businessValidator = businessValidator;
        }

        public async Task<StockAdjustmentDetailResponse> CreateAsync(CreateStockAdjustmentRequest request, long userId)
        {
            if (request.Items.Count == 0)
                throw new BusinessException("Stock adjustment must contain at least one item.", "SA014", StatusCodes.Status400BadRequest);

            await _businessValidator.ValidateWarehouseExistsAsync(request.WarehouseID);

            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(
                request.Items.Select(i => i.BatchID),
                request.WarehouseID);

            foreach (var item in request.Items)
            {
                _businessValidator.ValidateStockNotNegative(batches[item.BatchID], item.AdjustQuantity);
            }

            var adjustment = request.ToEntity(userId);
            adjustment.Status = StatusTicket.PENDING;

            adjustment.StockAdjustmentItem = request.Items
                .Select(item => item.ToEntity(0))
                .ToList();

            await _repository.AddAsync(adjustment);
            await _repository.SaveChangesAsync();

            return (await GetByIdAsync(adjustment.StockAdjustmentID))!;
        }

        public async Task<StockAdjustmentDetailResponse> UpdateAsync(long id, UpdateStockAdjustmentRequest request, long userId)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            if (adjustment == null)
                throw new BusinessException("Stock adjustment not found.", "SA013", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(adjustment);
            StatusTicketValidator.ValidateForUpdate(adjustment.Status, "điều chỉnh tồn kho");

            if (request.Items.Count == 0)
                throw new BusinessException("Stock adjustment must contain at least one item.", "SA014", StatusCodes.Status400BadRequest);

            await _businessValidator.ValidateWarehouseExistsAsync(request.WarehouseID);

            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(
                request.Items.Select(i => i.BatchID),
                request.WarehouseID);

            foreach (var item in request.Items)
            {
                _businessValidator.ValidateStockNotNegative(batches[item.BatchID], item.AdjustQuantity);
            }

            adjustment.WarehouseID = request.WarehouseID;
            adjustment.Note = request.Note;
            adjustment.Status = StatusTicket.PENDING;

            adjustment.StockAdjustmentItem = request.Items
                .Select(item => item.ToEntity(0))
                .ToList();

            await _repository.SaveChangesAsync();

            return (await GetByIdAsync(adjustment.StockAdjustmentID))!;
        }

        public async Task ApproveAsync(long id, long userId)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            if (adjustment == null)
                throw new BusinessException("Stock adjustment not found.", "SA013", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(adjustment);
            StatusTicketValidator.ValidateForApprove(adjustment.Status, "điều chỉnh tồn kho");
            StatusTicketValidator.ValidateCreatorNotApprover(adjustment.UserID, userId, "điều chỉnh tồn kho");

            adjustment.Status = StatusTicket.APPROVED;
            adjustment.ApprovedBy = userId;
            adjustment.ApprovedAt = DateTime.Now;

            await _repository.SaveChangesAsync();
        }

        public async Task RejectAsync(long id, long userId)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            if (adjustment == null)
                throw new BusinessException("Stock adjustment not found.", "SA013", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(adjustment);
            StatusTicketValidator.ValidateForReject(adjustment.Status, "điều chỉnh tồn kho");

            adjustment.Status = StatusTicket.REJECTED;

            await _repository.SaveChangesAsync();
        }

        public async Task DeleteAsync(long id, long userId)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            if (adjustment == null)
                throw new BusinessException("Stock adjustment not found.", "SA013", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(adjustment);
            StatusTicketValidator.ValidateForDelete(adjustment.Status, "điều chỉnh tồn kho");

            _repository.Delete(adjustment);
            await _repository.SaveChangesAsync();
        }

        public async Task<StockAdjustmentDetailResponse> CompleteAsync(long id, long userId)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            if (adjustment == null)
                throw new BusinessException("Stock adjustment not found.", "SA013", StatusCodes.Status404NotFound);

            _businessValidator.ValidateNotAutoGenerated(adjustment);
            StatusTicketValidator.ValidateForComplete(adjustment.Status, "điều chỉnh tồn kho");

            var items = adjustment.StockAdjustmentItem?.ToList() ?? new List<StockAdjustmentItem>();
            if (items.Count == 0)
                throw new BusinessException("Stock adjustment has no items.", "SA014", StatusCodes.Status400BadRequest);

            var batchIds = items.Select(i => i.BatchID).ToList();
            var batches = await _businessValidator.ValidateBatchesInWarehouseAsync(batchIds, adjustment.WarehouseID);

            await _repository.BeginTransactionAsync();
            try
            {
                foreach (var item in items)
                {
                    if (!batches.TryGetValue(item.BatchID, out var batch)
                        || batch.QuantityInStock + item.AdjustQuantity < 0)
                        throw new BusinessException(
                            $"Insufficient stock for batch ID {item.BatchID}.",
                            "SA012",
                            StatusCodes.Status400BadRequest);

                    batch.QuantityInStock += item.AdjustQuantity;
                }

                adjustment.Status = StatusTicket.COMPLETE;

                await _repository.SaveChangesAsync();
                await _repository.CommitTransactionAsync();
            }
            catch
            {
                await _repository.RollbackTransactionAsync();
                throw;
            }

            return (await GetByIdAsync(adjustment.StockAdjustmentID))!;
        }

        public async Task<StockAdjustmentDetailResponse?> GetByIdAsync(long id)
        {
            var adjustment = await _repository.GetByIdAsync(id);
            return adjustment?.ToDetailResponse();
        }

        public async Task<StockAdjustmentListResponse> GetAllAsync(int page, int count, long warehouseId)
        {
            var paged = await PaginationHelper.GetPagedAsync(
                (skip, take) => _repository.GetAllAsync(skip, take, warehouseId),
                () => _repository.CountAsync(warehouseId),
                page, count);

            return new StockAdjustmentListResponse
            {
                NumRecords = paged.NumRecords,
                TotalPage = paged.TotalPage,
                StockAdjustments = paged.Items.ToResponseList()
            };
        }
    }
}
