name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Test code
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Chạy Test
        run: echo "Bước Test thành công!"

  # Job 2: Đóng gói Container
  build-and-package:
    # job test-code phải thành công thì mới chạy
    needs: test-code 
    runs-on: ubuntu-latest
    
    # Cấp quyền cho GitHub Actions ghi file vào kho chứa Packages
    permissions:
      contents: read
      packages: write

    steps:
      - name: Kéo mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Docker Buildx (Công cụ hỗ trợ build nâng cao)
        uses: docker/setup-buildx-action@v3

      - name: Đăng nhập vào GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build và đẩy Image Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/namphu2810/supplychain_pharmacy-backend:latest
      - name: Build và đẩy Image Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/pharmacymanage
          push: true
          tags: ghcr.io/namphu2810/supplychain_pharmacy-frontend:latest
